export const USER_LIST_FETCHED = "USER_LIST_FETCHED";
export const USER_LIST_FILTER = "USER_LIST_FILTER";
export const USER_LIST_IS_FETCHING = "USER_LIST_IS_FETCHING";

export const ORG_LIST_FETCHED = "ORG_LIST_FETCHED";
export const ORG_LIST_FILTER = "ORG_LIST_FILTER";
export const ORG_LIST_IS_FETCHING = "ORG_LIST_IS_FETCHING";

export const KEY_LIST_FETCHED = "KEY_LIST_FETCHED";
export const KEY_LIST_FILTER = "KEY_LIST_FILTER";
export const KEY_LIST_IS_FETCHING = "KEY_LIST_IS_FETCHING";

export const INST_LIST_FETCHED = "INS_LIST_FETCHED";
export const INST_LIST_FILTER = "INS_LIST_FILTER";
export const INST_LIST_IS_FETCHING = "INS_LIST_IS_FETCHING";

export const FLAVOR_LIST_FETCHED = "FLAVOR_LIST_FETCHED";
export const FLAVOR_LIST_FILTER = "FLAVOR_LIST_FILTER";
export const FLAVOR_LIST_IS_FETCHING = "FLAVOR_LIST_IS_FETCHING";

export const IMAGE_LIST_FETCHED = "IMAGE_LIST_FETCHED";
export const IMAGE_LIST_FILTER = "IMAGE_LIST_FILTER";
export const IMAGE_LIST_IS_FETCHING = "IMAGE_LIST_IS_FETCHING";

export const SUB_LIST_FETCHED = "SUB_LIST_FETCHED";
export const SUB_LIST_FILTER = "SUB_LIST_FILTER";
export const SUB_LIST_IS_FETCHING = "SUB_LIST_IS_FETCHING";

export const FLOATINGIP_LIST_FETCHED = "FLOATINGIP_LIST_FETCHED";
export const FLOATINGIP_LIST_FILTER = "FLOATINGIP_LIST_FILTER";
export const FLOATINGIP_LIST_IS_FETCHING = "FLOATINGIP_LIST_IS_FETCHING";

export const GW_LIST_FETCHED = "GW_LIST_FETCHED";
export const GW_LIST_FILTER = "GW_LIST_FILTER";
export const GW_LIST_IS_FETCHING = "GW_LIST_IS_FETCHING";

export const SECGROUP_LIST_FETCHED = "SECGROUP_LIST_FETCHED";
export const SECGROUP_LIST_FILTER = "SECGROUP_LIST_FILTER";
export const SECGROUP_LIST_IS_FETCHING = "SECGROUP_LIST_IS_FETCHING";

export const SECRULE_LIST_FETCHED = "SECRULE_LIST_FETCHED";
export const SECRULE_LIST_FILTER = "SECRULE_LIST_FILTER";
export const SECRULE_LIST_IS_FETCHING = "SECRULE_LIST_IS_FETCHING";

export const OCP_LIST_FETCHED = "OCP_LIST_FETCHED";
export const OCP_LIST_FILTER = "OCP_LIST_FILTER";
export const OCP_LIST_IS_FETCHING = "OCP_LIST_IS_FETCHING";

export const REG_LIST_FETCHED = "REG_LIST_FETCHED";
export const REG_LIST_FILTER = "REG_LIST_FILTER";
export const REG_LIST_IS_FETCHING = "REG_LIST_IS_FETCHING";

export const REG_LIST_FETCH_FAILED = "REG_LIST_FETCH_FAILED";

export const REG_LIST_DELETE_FAILED = "REG_LIST_DELETE_FAILED";
export const REG_LIST_DELETING = "REG_LIST_DELETING";
export const REG_LIST_DELETE_SUCCESS = "REG_LIST_DELETE_SUCCESS";
